version: "3.7"
services:
  meana_api:
    container_name: "meana_api"
    image: "node"
    user: "node"
    working_dir: /home/node/app
    environment:
      - NODE_ENV=production
    volumes:
      - ../:/home/node/app
    ports:
      - "3333:3333"
    restart: always
    command: "npm run startAll"
  postgres:
    image: "timescale/timescaledb-ha:pg14-latest"
    environment:
     - POSTGRES_PASSWORD=password
    volumes:
     - postgres:/home/postgres
    restart: always
  rabbitmq:
    image: rabbitmq:3-management
    hostname: rabbitmq
    volumes:
     - /var/lib/rabbitmq
    restart: always
    environment:
     - RABBITMQ_DEFAULT_USER=admin
     - RABBITMQ_DEFAULT_PASS=admin

volumes:
  postgres:
