version: "3.7"
services:
  meana_api:
    container_name: "meana_api"
    image: "node"
    user: "node"
    working_dir: /home/node/app
    environment:
      - NODE_ENV=production
    volumes:
      - ../:/home/node/app
    ports:
      - "3333:3333"
    restart: always
    command: "npx nx serve api"
  meana_api_agent:
    container_name: "meana_api_agent"
    image: "node"
    user: "node"
    working_dir: /home/node/app
    environment:
      - NODE_ENV=production
    volumes:
      - ../:/home/node/app
    ports:
      - "3334:3334"
    restart: always
    command: "npx nx serve api-agent"
  meana_notification_service:
    container_name: "meana_notification_service"
    image: "node"
    user: "node"
    working_dir: /home/node/app
    environment:
      - NODE_ENV=production
    volumes:
      - ../:/home/node/app
    restart: always
    depends_on:
      - "rabbitmq"
    command: "npx nx run notification-service:run-script:run"
  meana_threshold_service:
    container_name: "meana_threshold_service"
    image: "node"
    user: "node"
    working_dir: /home/node/app
    environment:
      - NODE_ENV=production
    volumes:
      - ../:/home/node/app
    restart: always
    depends_on:
      - "rabbitmq"
    command: "npx nx run threshold-value:run-script:run"
  postgres:
    image: "timescale/timescaledb-ha:pg14-latest"
    environment:
     - POSTGRES_PASSWORD=password
    volumes:
     - postgres:/home/postgres
    restart: always
    ports:
      - "5434:5432"
  rabbitmq:
    image: rabbitmq:3-management
    hostname: rabbitmq
    volumes:
     - /var/lib/rabbitmq
    ports:
     - "5672:5672"
     - "15672:15672"
    restart: always
    environment:
     - RABBITMQ_DEFAULT_USER=admin
     - RABBITMQ_DEFAULT_PASS=admin

volumes:
  postgres:
