version: "3.7"
services:
  postgres:
    image: "timescale/timescaledb-ha:pg14-latest"
    environment:
     - POSTGRES_PASSWORD=password
    volumes:
     - postgres:/home/postgres
    ports:
      - "5434:5432"
  rabbitmq:
    image: rabbitmq:3-management
    hostname: rabbitmq
    volumes:
     - /var/lib/rabbitmq
    ports:
     - "5672:5672"
     - "15672:15672"
    environment:
     - RABBITMQ_DEFAULT_USER=admin
     - RABBITMQ_DEFAULT_PASS=admin

volumes:
  postgres:
