version: "3.7"
services:
  postgres:
    image: "timescale/timescaledb-ha:pg14-latest"
    environment:
     - POSTGRES_PASSWORD=password
    volumes:
     - postgres:/home/postgres
    ports:
      - "5434:5432"

volumes:
  postgres:
